services:
  mongo_db_catalog:
    image: mongo:6.0
    container_name: mongo_db_catalog.container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27030:27017"
    volumes:
      - mongo_db_catalog_volume:/data/db

  mongo_db_catalog_ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo_db_catalog.ui
    depends_on:
      - mongo_db_catalog
    ports:
      - "27032:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo_db_catalog
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo_db_catalog:27017/

volumes:
  mongo_db_catalog_volume: